name: AWS example workflow

on:
  push

env:
  AWS_REGION : "ap-northeast-2"

permissions:
  id-token: write   
  contents: read    

jobs:
  Deloy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_NAME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Make .zip
        run: |
          zip -r deployment_package.zip . 

      - name: Upload .zip to Amazon S3
        run: |
          aws s3 cp deployment_package.zip s3://${{ secrets.BUCKET_NAME }}/$GITHUB_SHA.zip

      - name: Create deployment to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.CODEDEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ secrets.DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ secrets.BUCKET_NAME }},key=$GITHUB_SHA.zip,bundleType=zip \
            --file-exists-behavior OVERWRITE